### PR TITLE
Upgrading to jbake-2.6.4

### PR DESCRIPTION
**Pull request by vieiro**
This is an upgrade to the latest version of jBake.

### CODE REVIEW

**Comment by vieiro** [comment]
Thanks, @shivaylamba!
I think there're some bad names in templates, let me fix them first.

**Comment by vieiro** [comment]
Template titles in comments are not right, I'm afraid!

**Comment by vieiro** [comment]
New version of jbake is 2x slower than the previous one. This requires investigation.

**Comment by WinterSilence** [comment]
изображение
what's is? and how it's work?

**Comment by ebarboni** [comment]
Hi @WinterSilence , This is a pull request, not a issue tracker,  I suggest that you remove your offtopic comment. This thread is about NetBeans web page building. If you have issue with Apache NetBeans please report using JIRA, Thanks

**Comment by vieiro** [comment]
> изображение
> what's is? and how it's work?

That's the new Language Server Protocol dialog.

**Pull request closed without merging**
