### PR TITLE
Added missing v2.8 dtd for new autoupdate-catalog

### PR DESCRIPTION
**Pull request by lkishalmi**

### CODE REVIEW

**Comment by lkishalmi** [comment]
This is in the auto update code, and yes it is in the source code in NetBeans.
It is only an issue if you would like to hack something quick and dirty to merge updates.xmls.
Also for the shake of completeness.

**Comment by neilcsmith-net** [comment]
> It is only an issue if you would like to hack something quick and dirty to merge updates.xmls

Ah, cool, you're looking at that.  Been on my to-do list for a while - look forward to seeing it.

**Comment by vieiro** [comment]
Infra is restarting Jenkins, so please allow some time for this to be live.

**Comment by neilcsmith-net** [comment]
@vieiro ah, apologies if that was an inopportune time to merge.

**Comment by vieiro** [comment]
@neilcsmith-net On the contrary, it's a good opportunity to see how the job is queued https://ci-builds.apache.org/job/Netbeans/job/netbeans-website/ when jenkins is being shut down (it's taking hours) and how it's then resumed when jenkins restarts... :-)

**Comment by vieiro** [comment]
For the records: no, it doesn't resume jobs if Jenkins is shutdown.

**Pull request merged**
