### PR TITLE
fix images for quickstart_platform tutorial

### PR DESCRIPTION
**Pull request by ebarboni**
recovered image from commit [023d7dad4edf5981e76857efcbe98e486a093691](https://github.com/apache/netbeans-website/commit/023d7dad4edf5981e76857efcbe98e486a093691)

renamed with prefix without version.
removed former platform 73 (they are also in old content)

### CODE REVIEW

**Comment by mbien** [comment]
i am a bit confused what is happening here ;/

for example, you removed:
https://github.com/apache/netbeans-website/blob/f03ab9809fab1bf7755ab9b92ef37615ca973793/netbeans.apache.org/src/content/tutorials/images/quickstart-platform_73_new-api-1.png

and added:
https://github.com/apache/netbeans-website/blob/10170847062a64cb7024556aeb0ca97198a72c24/netbeans.apache.org/src/content/tutorials/images/quickstart_platform_new-api-1.png

the first one looks to be properly sized, which probably means that it is more recent?

**Comment by mbien** [comment]
but tbh maybe thats how it is supposed to be? Can we test this somehow if everything works before merging?

**Comment by ebarboni** [comment]
sorry I had to force push. I was using a bad clone with wrong file name.  
https://github.com/apache/netbeans-website/blob/6720139f8c15a51068be35636a7bb617e5a5141f/netbeans.apache.org/src/content/tutorials/nbm-quick-start.adoc  may give a preview.
this is intended to respect addition https://github.com/apache/netbeans-website/pull/500

**Comment by mbien** [comment]
seems to work now. Although some pictures are too large for their purpose.

i believe what happened that the repo had two kinds of screenshots: the original with the whole component and then smaller versions which showed only a small part of it, this explains:
https://github.com/apache/netbeans-website/pull/648#issuecomment-1460609310

this PR uses the full version of the screenshots now, which is better than nothing but looks a bit ugly sometimes e.g:
https://github.com/apache/netbeans-website/blob/6720139f8c15a51068be35636a7bb617e5a5141f/netbeans.apache.org/src/content/tutorials/nbm-quick-start.adoc#create-the-module

**Comment by ebarboni** [comment]
inclined to merge and let "photoshop" expert crop :D. There is no tools to "automate" screen shot ?  Would be more deterministic.

**Comment by mbien** [comment]
what if we leave the small pictures in the repo? so that someone could rename/switch to them on a case by case basis?

**Comment by ebarboni** [comment]
they are in the repo at
 https://github.com/apache/netbeans-website/tree/master/netbeans.apache.org/src/old_content/content/tutorials/80/images
and maybe others version.
https://netbeans.apache.org/tutorials/80/nbm-quick-start.html the previous one ( from version 8.0)

I think #500 was also adding new screenshot/content
but the screenshot are missing from ages in the "main" tuto track. 

I have not webarchive with valid screen on it. 

https://web.archive.org/web/20210518050646/https://netbeans.apache.org/tutorials/nbm-quick-start.html

**Comment by mbien** [comment]
oh wow, didn't know that there is another copy of them in the repo - excellent lets merge :)

**Review by mbien — APPROVED** [review]

**Comment by mbien** [comment]
the tutorial has now gigantic windows :)
https://netbeans.apache.org/tutorials/nbm-quick-start.html

**Pull request merged**
