### PR TITLE
a few code block rewrite to get it pretty

### PR DESCRIPTION
**Pull request by ebarboni**
I wanted to fix https://github.com/apache/netbeans/issues/4520
But I fix a bit more files. 

IF subs=macros is used,  <> clash with parser I guess so it should be rewritted as javadoc with &lt;.

I try to keep the *bold* in the code to see how it render but I thinks it's not very readable.
I tweak the tutorials/nbm-projecttypeant.html to use hash to get it in yellow and see difference.

I guess we need some helper like in #537

### CODE REVIEW

**Comment by mbien** [comment]
is there no better way of doing this? Manually escaping characters in documentation code can be fairly annoying and is easy to overlook in updates.

I wrote a plugin for apache roller which can escape `<pre>` and `<code>` segments automatically, all I have to do is to paste code into my blog the rest is done before it is translated to html. I am wondering if jbake can do the same?

**Comment by ebarboni** [comment]
forget to read the doc, using verbatim in subs do the trick.

**Review by vieiro — APPROVED** [review]
Everything looks sane to me (did a quick look, though).
We should start dropping those /71, /69, /73, etc. folders: that content for previous NetBeans versions is ok for having a history, but we won't be maintaining them any longer.

**Comment by vieiro** [comment]
@mbien , @ebarboni , You're right: no need to quote stuff in asciidoc, verbatim just works.

**Comment by ebarboni** [comment]
I will merge this.
Was thinking on moving locale to localfolder for non english like pt-PR a bit like last paragrah on https://maven.apache.org/plugins/maven-site-plugin/examples/creating-content.html so source will have smaller file per folder (the build system could put the mess back :D)

For the old tutorial I think we should move them inside the git but they should not be published. Better not have them live than having 404.

**Review by mbien — APPROVED** [review]

**Pull request merged**
