### PR TITLE
bump version for jquery, gradle + cleanup css/js from previous site

### PR DESCRIPTION
**Pull request by ebarboni**
Hi, 
this is housekeeping PR.

gradle updated to 8.3.
some fixes in scss to remove warning. (Maybe we should update to current last version of motion-ui)
bump jquery to 3.7.1 (min and normal)

remove v4/v7/v6 former resource that we are not using anymore , webarchive use their own data for that.

website seems to look the same as before.

### CODE REVIEW

**Comment by ebarboni** [comment]
@vieiro @mbien could I make a test ?

**Comment by vieiro** [comment]
@ebarboni sure! We can always roll-back the thing, right? go for it!

**Comment by ebarboni** [comment]
lets try

**Comment by ebarboni** [comment]
I agree, for both "paperwork" and testing.

But I cannot say why it works on localmachine, using same jdk but it later fail on CI.

**Comment by ebarboni** [comment]
@mbien @vieiro  If you have time to build the current master on your system, I'm desperate. Locally it works well, from gradle 7.5.1 to 8.3. But if it come to github action (I tried a PR) or jenkins it fails.

**Comment by vieiro** [comment]
Hi there,

This repo is getting huge. It's ~ half a gigabyte. We should consider alternative build procedures or split this into different repositories. Maybe we want to give Antora a try? 

I think the SASS plugin is to blame, IIRC this uses `libsass` to compile the SCSS natively, so maybe libsass is required in the system. I do have `sassc` and `libsass1` in my Ubuntu system, but I think the following command fails:

```
$ ./gradlew --stacktrace --debug compileContentSass
```

In fact no css is produced in `build/generated-bake/assets/css`.

AFAIK there're little options to successfully compile SCSS in Java. Maybe we need another plugin version or something? What about moving this to a more `frontend friendly` build system such as node?

**Comment by ebarboni** [comment]
it's works on my box :/ I'm so bored for that

antora + node  could be nice. No expert but could try.

We will not loose ascidoc. How to split ? make old content / non english page on another repo ? and build only the english pages + last version tutorial for a while ?

**Pull request merged**
