### PR TITLE
Fix the daily build links

### PR DESCRIPTION
**Pull request by junichi11**

### CODE REVIEW

**Review by neilcsmith-net — CHANGES_REQUESTED** [review]
Linux link looks good.  Windows build isn't currently keeping artefacts (cc. @ebarboni )?  Having both confuses people anyway, as sometimes Windows people think they need the Windows build.  Maybe link to the Linux one but just call it the daily build?  And longer term think we should move daily build with NetBeansTLP instead.

**Comment by junichi11** [comment]
I've just changed the existing URLs. I'll remove the windows link later if other people have no opinion. Thanks.

**Comment by errael** [comment]
Perhaps OT. But I just added these instructions to an issue as part of encouraging some testing for a recent PR added to master. I otherwise didn't see any instructions on getting/running a daily build. Not sure where the instructions should go

> The as yet undocumented location of the build artifacts is
> 
> https://ci-builds.apache.org/job/Netbeans/job/netbeans-linux
> 
> With that starting point
> 
> 1. Click "Last Successful Artifacts" or something in
>    the "Build History" list on the left
> 2. Then traverse "nbbuild > NetBeans-dev-Netbeans
> 3. download netbeans-linux-...-release.zip
> 
> This should run on windows as well as linux, AFAICT.

**Comment by junichi11** [comment]
@errael Nice idea :) I think we should merge that as your contribution. So, could you please create a PR for that after this is fixed?

**Comment by junichi11** [comment]
@neilcsmith-net Just removed the windows link.

**Comment by errael** [comment]
@junichi11 On the same page that this PR is modifying?

**Comment by junichi11** [comment]
@errael Maybe, Yes.

**Review by neilcsmith-net — APPROVED** [review]

**Pull request merged**
