### PR TITLE
Some formatting and mvn plugin version update

### PR DESCRIPTION
**Pull request by mawasak**
1. Some formatting
2. Version changed for RELEASE81

### CODE REVIEW

**Comment by ebarboni** [comment]
Hi @mawasak, thanks for handling that. 

If possible for you it would be nice to change to the very last nbmplugin
<groupId>org.apache.netbeans.utilities</groupId>
 <artifactId>nbm-maven-plugin</artifactId>
                <version>4.5</version>

and very last release of NetBeans is RELEASE120-1

https://repo1.maven.org/maven2/org/apache/netbeans/archetypes/
contains all archetype under Apache 
https://repo1.maven.org/maven2/org/apache/netbeans/utilities/
contains all plugins under Apache

**Comment by mawasak** [comment]
Hi,
I will check it.

**Comment by mawasak** [comment]
Hi, I updated tutorial as you described.

**Comment by neilcsmith-net** [comment]
cc @ebarboni - could you have another look here?

**Review by ebarboni — APPROVED** [review]
looks ok , a bit late

**Comment by neilcsmith-net** [comment]
Thanks @ebarboni and @mawasak .  I'll merge, please check over when published.

**Comment by mawasak** [comment]
@neilcsmith-net - when will it be published? It has old version https://netbeans.apache.org/tutorials/nbm-maven-commandline.html

**Comment by neilcsmith-net** [comment]
@mawasak should have happened in space of 10 minutes or so.  Sorry, won't be able to check for a while - @ebarboni is the publishing stuck again?

**Pull request merged**
