### PR TITLE
Update quickstart-gui.adoc: Link and bold typo

### PR DESCRIPTION
**Pull request by christoph-petzold**
- try to fix section link, see: https://github.com/apache/netbeans-website/pull/634#issuecomment-1387705785
- fix bold white space typo

### CODE REVIEW

**Comment by christoph-petzold** [comment]
The way in which the asciiDoc link ids are generated differs between github preview and the website. Github uses this-kind-of-id in the website it is _this_kind_of_id.

So one cannot rely on the preview in this context.

**Comment by mbien** [comment]
@christoph-petzold I should have known better since I made the same mistake before, sorry.

**Review by mbien — APPROVED** [review]

**Comment by christoph-petzold** [comment]
This time it worked, thank you @mbien! This is my first little commit and pull request in github. I am proud and happy to see the improvemt on the page in the website. This is so cool!

**Comment by mbien** [comment]
@christoph-petzold it worked! The bold bits too.

**Comment by mbien** [comment]
@christoph-petzold congrats to your first contribution! :)

**Comment by ebarboni** [comment]
many thanks and do not hesitate if you find others !

**Pull request merged**
