### PR TITLE
Revised editor-inspect-transform.asciidoc

### PR DESCRIPTION
**Pull request by JeremyCavanagh**
Proposed rewrite

### CODE REVIEW

**Comment by geertjanw** [comment]
Awesome, but there appear to be conflicts with other files.

**Comment by vieiro** [comment]
Hi all,
Yep, those conflicts with the master branch have to be solved somehow. I can't help out during this week, so I'd suggest moving to another tutorials meanwhile.
There're some instructions at https://github.com/apache/incubator-netbeans-website/pull/319 about git usage, that can be of help.
Cheers,
Antonio

**Comment by vieiro** [comment]
Jeremy, please try to create a PR for each tutorial, otherwise we'll be piling up changes of top of a single PR!

**Comment by geertjanw** [comment]
Yes, please do one tutorial per PR.

**Comment by vieiro** [comment]
Closing after more than one month of inactivity. @JeremyCavanagh please feel free to create a new PR with per/tutorial modifications. Thanks!.

**Pull request closed without merging**
