### PR TITLE
Self host fonts

### PR DESCRIPTION
**Pull request by matthiasblaesing**
According to https://privacy.apache.org/faq/committers.html fonts should not be imported from google fonts by using the google API. Instead the fonts should be hosted by the project itself.

This PR imports the two referenced fonts from google and updates the references to the local copy.

### CODE REVIEW

**Comment by ebarboni** [comment]
nice finding, looks ok to me

**Comment by neilcsmith-net** [comment]
Good find, thanks.  Not sure if something changed or we missed this at the time.

I'm curious to see that old splash image in there!  Either needs updating or removing at some point.

**Comment by matthiasblaesing** [comment]
I was triggered by this: https://github.com/apache/apache-website-template/issues/16 -- Initially I though the issue was filed against one of the NetBeans repositories. When I found, that another repository was affected I decided to continue the investigation anyway and get this out.

**Comment by ebarboni** [comment]
I didn't remember this whimsy tool :D. Now it's green for us but was supposed to warn for external.

https://whimsy.apache.org/site/project/netbeans

**Pull request merged**
