### PR TITLE
Add known problems section to NB12 with workaround for maven caching problem

### PR DESCRIPTION
**Pull request by matthiasblaesing**

### CODE REVIEW

**Comment by geertjanw** [comment]
Great.

**Comment by matthiasblaesing** [comment]
@vieiro thanks for the hint. ini did not work for me, but just for luck it is also valid bash. I had to update the template as it did not include the necessary js library.
@geertjanw nice timing :-)

**Comment by neilcsmith-net** [comment]
> but just for luck it is also valid bash.

Not really luck, that's exactly what it is! :smile:

Having the whole line feels a bit text heavy, but I guess has benefits - we really need to work on a better solution to passing all those options!

Thanks for adding this!  Might be good place to add (another) comment about not enabling nb-javac with JDK 14?

**Comment by geertjanw** [comment]
That’s already prominently as a tip in the Features page, but maybe good to have as well in a Troubleshooting section.

**Comment by neilcsmith-net** [comment]
@geertjanw yes, I saw that - sorry, subtle reference to "another".  Just thought having a single place for listing all known problems / workarounds is a good approach.  Then also linking through to eg. http://netbeans.apache.org/download/nb120/nb120.html#_known_problems from elsewhere.

Aside - those subsection links seem odd - expected it to be `#known-problems`

**Pull request merged**
