### PR TITLE
Creat info.text file

### PR DESCRIPTION
**Pull request by cunka**
Add to new folder to indicate what images are used in what help file. - in this case its the Visual Debugger help file. (https://netbeans.apache.org/kb/docs/java/debug-visual.html)

The Visual Debugger tutorial requires new images. The new images will be uploaded into this folder.
The help file will be updated with the new images.

### CODE REVIEW

**Comment by cunka** [comment]
I should have added to the Pull Request that I have the images already completed for the new Visual Debugger tutorial. I need the folder in place, so I can upload the images into it, then link them in the document.

**Comment by vieiro** [comment]
Hi @cunka,
Please try to keep images in the "images/" subdirectory directly. No nesting, please. Also use lower case names for all assets. If you're afraid of name clashing you can always prefix images with "visualdebugger". 

For instance, "images/VisualDebugger/image1.png" should be "images/visualdebugger-image1.png"

Also please try to keep PRs self contained: add images to this PR, and do not delay that for a future PR.

Thanks!
Antonio

**Comment by cunka** [comment]
Add these images
VisualDebug_image1
VisualDebug_image2
VisualDebug_image3
VisualDebug_image4
VisualDebug_image5
VisualDebug_image6
VisualDebug_image24
VisualDebug_image23
VisualDebug_image22
VisualDebug_image21
VisualDebug_image20
VisualDebug_image19
VisualDebug_image18
VisualDebug_image17
VisualDebug_image16
VisualDebug_image15
VisualDebug_image14
VisualDebug_image13
VisualDebug_image12
VisualDebug_image11
VisualDebug_image10
VisualDebug_image9
VisualDebug_image8
VisualDebug_image7

**Comment by vieiro** [comment]
Hi @cunka ,
Please copy these images in the "images" subdirectory near the tutorial (in your hard disk). Give these images proper names you see fit. Afterwards modify the .asciidoc file to point to these images.
Once things render property do a "git add images/*.png", then a "git commit -m 'Images'" and then a "git push".

**Comment by vieiro** [comment]
Closed after more than one month of inactivity.

**Pull request closed without merging**
