### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by ebarboni**
use https

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
@ebarboni have you tested?  The old plugin centre can't handle https as far as I know. Maybe something to discuss on dev@ - should be new plugin centre yet?

**Comment by ebarboni** [comment]
Well for now I have an issue like that :
Unable to connect to the NetBeans Plugin Portal because of Redirect from secure URL 'https://netbeans.apache.org/nb/plugins/11.3/catalog.xml.gz' to 'http://plugins.netbeans.org/nbpluginportal/updates/11.0/catalog.xml.gz' blocked.

I guess it may help but, not sure

**Comment by ebarboni** [comment]
maybe I miss a redirect on the vm, I was not sure of the step .

**Comment by lalo-mx** [comment]
The URL is failing:

> 502  Proxy Error
> Proxy Error
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request
> 
> Reason: Error reading from remote server

**Comment by neilcsmith-net** [comment]
@lalo-mx yes, the upstream server is down - nothing that can be done at Apache end unfortunately.

**Pull request merged**
