### PR TITLE
Remove past events and add dates for 2019

### PR DESCRIPTION
**Pull request by markee174**
I have added CodeOne 2019 NetBeans links, DawsCon and NetBeans UK2019. I have also removed old 2018 entries but added some write-ups to previous events

### CODE REVIEW

**Comment by vieiro** [comment]
Hi @markee174 ,
Would it be possible to create a "Past Events" section and keep the past events there?
As the lists grows we may want to create a separate page for past events.
Thanks,
Antonio

**Comment by markee174** [comment]
Good idea. I would like to post this update, promote it and get some general feedback and then do some more updates. I was also going to suggest we post reviews/write-up of previous events (I ad done by Ken and Ovi to my changes)

**Comment by geertjanw** [comment]
Sounds good. Going to merge this now and you can take it from there. :-)

**Comment by markee174** [comment]
Added Past events as patch 3 - pull request submitted  (also fixes a silly mistake on my part) @geertjanw

**Pull request merged**
