### PR TITLE
Jbake 2.6.7 and gradle 7.5.1

### PR DESCRIPTION
**Pull request by ebarboni**
Move to a more modern gradle so we can use modern jdk to build the website.

Use latest jbake and jbake plugin to get rid of jcenter

default gradle script and wrapper folder changes were done by gradle update

### CODE REVIEW

**Comment by mbien** [comment]
adding @lkishalmi since he is our gradle guru I believe :)

**Review by vieiro — CHANGES_REQUESTED** [review]
Hi @ebarboni ,
I tried this in my Linux box, and I get this error:

```
2022-10-04T21:00:33.685+0200 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting build in new daemon [memory: 512 MiB]
2022-10-04T21:00:33.693+0200 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
2022-10-04T21:00:33.694+0200 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=255d0a21-9a02-4a0d-b16f-4aebfcd9f095,javaHome=/home/antonio/SOFTWARE/jdk-11.0.14.1+1,daemonRegistryDir=/home/antonio/.gradle/daemon,pid=566471,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=ES,-Duser.language=es,-Duser.variant]
----- End of the daemon log -----


FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
```

Does this work for you on Linux?

**Comment by ebarboni** [comment]
I have no 100% linux, wsl only but was working

**Comment by vieiro** [comment]
I'll try to run this on another Linux box of mine during next weekend. Let's see if this is a problem of mine or what.

**Comment by ebarboni** [comment]
spurious OOM daemon but also on gradle 6.x.

**Comment by mbien** [comment]
have you tried giving it a bit more heap? I saw that it is set to 64mb could be a bit low for groovy.

**Comment by ebarboni** [comment]
how you do that ?

**Comment by vieiro** [comment]
@ebarboni Maybe we want to change

```
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
```

to

```
DEFAULT_JVM_OPTS='"-Xmx1024m" 
```

**Comment by ebarboni** [comment]
with new parameters: no more annoyance on jdk 11 / WSL 2. Hope it will works for others

**Comment by vieiro** [comment]
Hi @ebarboni .
It seems this is something related to my Linux box. I tried with the `./gradlew --no-daemon clean build` and things worked correctly.
Please rollbback the memory changes (these afect only to the gradlew script, not to daemons, affer all) and feel free to merge.

**Comment by ebarboni** [comment]
ok commit removed merging

**Comment by ebarboni** [comment]
well updated directly the jenkins file but seems the issue match the one you get. Maybe we shoud upgrade the memory

**Comment by ebarboni** [comment]
worked and it's also more verbose than when it's saying heap size error :/

Seeing a bunch of thoose line I never add on my box
DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("shake")) instead.

**Pull request merged**
