### PR TITLE
[NETBEANS-2455] Splash screen in SVG

### PR DESCRIPTION
**Pull request by vieiro**
Updating the splash screen SVG to render everywhere.
Also a PNG file is included.

### CODE REVIEW

**Comment by vieiro** [comment]
Hi guys, some sample splash screens for NETBEANS-2455, what do you say? Do you like these?

**Comment by Chris2011** [comment]
Dont forget the little text that will be printed out like: start loading modules, done loading modules, etc. And the progressbar

**Comment by Chris2011** [comment]
I like it more to have Apache above NetBeans, Not as big as NetBeans and IDE is Missing. My 2 Cents.

**Comment by vieiro** [comment]
Thanks @Chris2011, will take that into account. Maybe a white bottom area to have the running text is the way to go. Will update the PR with that in the next days.

**Comment by vieiro** [comment]
Hi all, so it seems everybody has her own requirements.
Let's try to quickly (24/48h) see which the requirements are at https://issues.apache.org/jira/browse/NETBEANS-2455, I'm closing this now.

**Pull request closed without merging**
